make brightness adjust with inverse log instead of linear
JustEnoughLinuxOS/distribution pull request #2129
Opened 2023-09-29 01:27 UTC by Percentnineteen

# Pull Request Template

## Description

This code changes the brightness to weight the lower end of the brightness range more heavily than the upper end of the range. There are two main new functions added for possible future tweaks if a different ratio was found to be desirable:
eqn() - an equation that calculates the size of any given step
compute() - takes eqn() and scales it into the functional brightness range (MAX - MIN), then performs a ceiling operation

If the original behavior were desired, for instance, you could just change eqn to 1-(STEP/MAX).

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested Locally?

I built dev with and without my change and flashed to 2 separate sd cards and booted a RG353V with each. The minimum brightness appeared ~50% as bright as the existing dev. I only have one device so it was a very subjective test.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2023-09-29 02:43 UTC, littleguy77 commented
I suggest adding a link to https://discord.com/channels/948029830325235753/1154442821621776434 in the comments.  Some good discussion there that would explain things in case tweaks ever need to be made.

(I'm a sucker for documentation and breadcrumbs)

2023-09-29 03:23 UTC, Percentnineteen commented
Very good point linking to the discord discussion. I always forget you can do that with discord. I think of it as being more like a chat app than anything else...

I did find some odd behavior in the system settings menu that I want to iron out...or at least look at. That menu adjusts by increments of 10% (but normally displays the "real" percentage value). So, by default, if you use the hotkey to go down to the first brightness level and open system settings, you will see 4%. If you press right to increment, it updates to 14% instead of 8%.

Converting to a draft.

2023-09-30 02:44 UTC, Percentnineteen commented
made an emulation station tweak to display as x/10 instead of as a percentage. Also made it so that the values are consistent between using hotkeys and using the system settings.

2023-10-01 22:08 UTC, Percentnineteen commented
Sorry for all the churn. I have made a pretty major rework here that should satisfy most everyone.

I read a setting from system.cfg (brightness_table) and use that table to determine the number and distribution of brightness values to use. This is represented in the system menu as well as through hotkeys. If the user has not specified a table, then the default will be used:
0 0.04 0.08 0.13 0.19 0.25 0.33 0.42 0.54 0.71 1

If the user is unhappy with the inverse log values, they are welcome to:
1. ssh into the device
2. set_setting brightness_table "<their own list of values>"

If you were a savage,  you could use "0 1" to only use the dimmest or brightest possible settings. If you only want super dim options, you could use "0.01 0.02 0.03 0.04" and you would only have those 4 options available. I didn't test more than 20 values, but that worked fine. They don't even have to be linear if you wanted to be truly chaotic.

2023-10-02 12:01 UTC, fewtarius requested changes

2023-10-02 12:01 UTC, fewtarius commented on packages/ui/emulationstation/patches/001-tweak-brightness.patch
Let's PR this into EmulationStation.

2023-10-02 19:55 UTC, fewtarius approved these changes

2023-10-02 19:55 UTC, merged