Usb gadget implementation proposal
JustEnoughLinuxOS/distribution pull request #2399
Opened 2023-11-20 13:43 UTC by citral23

This PR proposes to lay a base to enable connecting JELOS devices over USB to a PC and be able to ssh to them directly

The scripts can be easily extended later to:
Add MTP function for people to easily transfer files in the same manner
Add RDNIS if desirable for PC with Windows < 10 (current ECM proposal works on linux, mac and Win > 10)

What it doesn't do for now is actually allow users to enable the function, other than doing themselves a "usb start cdc" from a shell, as a gui implementation needs a separate PR for ES.

2023-11-23 10:44 UTC, fewtarius requested changes

2023-11-25 10:24 UTC, citral23 commented
I followed the recommended formatting and naming convention for both scripts, and simplified autostart.
Tested working, let me know if anything else could be done better :)

2023-11-25 10:58 UTC, citral23 commented on packages/jelos/sources/scripts/usbgadget
> +		echo "Usage: usb [start|stop|restart]"
Right, my bad, updated

2023-11-25 17:43 UTC, fewtarius approved these changes

2023-11-25 17:43 UTC, merged